name: Build papermill component image

on:
  pull_request:
    paths:
      - 'papermill/*'
      - 'papermill/fuse/*'
      - 'production/common.py'
  push:
    branches: [main]
    paths:
      - 'papermill/*'
      - 'papermill/fuse/*'
      - 'production/common.py'

jobs:
  build:
    runs-on: ubuntu-latest

    # see https://github.com/docker/build-push-action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Copy production code
        run: |
          cp production/common.py papermill/
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          context: ./papermill/
          tags: |
            blsq/openhexa-papermill:latest
